#!/bin/sh
#
# Perform necessary nodex-agent setup steps
# before package is installed.
#

set -e

BIN_INSTALL_PATH=/home/nodex/bin/nodex-agent

if [ -f "$BIN_INSTALL_PATH" ]; then
    echo "Backing up existing ..."
    cp -r "$BIN_INSTALL_PATH" "$BIN_INSTALL_PATH.backup"
fi

echo "You're about to install nodex-agent!"

exit 0
