#!/bin/sh
#
# Perform necessary nodex-agent setup steps
# after package is installed.
#

INSTALL_DIR=/opt/nodex-agent
SERVICE_NAME=nodex-agent
CONFIG_DIR=~/.config/nodex

# Check if the user and group already exist, if not, create them
if ! id -u nodex >/dev/null 2>&1; then
    echo "Creating dedicated user and group for nodex-agent..."
    useradd -r -s /bin/false nodex
else
    echo "User nodex already exists."
fi

# Set ownership and permissions
chown -R root:nodex ${INSTALL_DIR}
chmod -R 750 ${INSTALL_DIR}

# Create a symlink to the agent's binary, handling existing symlink
if [ -L /usr/bin/nodex-agent ]; then
    echo "Updating existing symlink for nodex-agent..."
    ln -sf $INSTALL_DIR/bin/nodex-agent /usr/bin/nodex-agent
elif [ -e /usr/bin/nodex-agent ]; then
    echo "A file already exists at /usr/bin/nodex-agent. Removing it to create a symlink..."
    rm /usr/bin/nodex-agent
    ln -sf $INSTALL_DIR/bin/nodex-agent /usr/bin/nodex-agent
else
    echo "Creating a new symlink for nodex-agent..."
    ln -sf $INSTALL_DIR/bin/nodex-agent /usr/bin/nodex-agent
fi

# Reload systemd to recognize the new service
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
else
    echo "[ WARNING ]\tCannot detect a supported init system. The nodex-agent package only provides service files for systemd"
fi

# Enable and start the service
echo "Enabling service $SERVICE_NAME"
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable $SERVICE_NAME
fi

if [ -f "$CONFIG_DIR" ]; then
    echo "(Re)starting $SERVICE_NAME now..."
    if command -v systemctl >/dev/null 2>&1; then
        systemctl restart $SERVICE_NAME || true
    else
        echo "[ WARNING ]\tCannot detect a supported init system. The nodex-agent package only provides service files for systemd"
    fi
else
    if command -v systemctl >/dev/null 2>&1; then
        systemctl start $SERVICE_NAME || true
    else
        echo "[ WARNING ]\tCannot detect a supported init system. The nodex-agent package only provides service files for systemd"
    fi
fi

echo "Nodex Agent Service has been installed and started."
echo "Thank you for installing nodex-agent!"

exit 0
