services:
  mock_studio:
    build:
      context: ./mock_studio
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    environment:
      RUST_LOG: debug
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8020/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  systemd_test:
    depends_on:
      mock_studio:
        condition: service_healthy
    build:
      context: .
      dockerfile: systemd/Dockerfile
    privileged: true
    profiles:
      - systemd
    volumes:
      - ./config:/root/.config/nodex/
      - agent_socket:/root/.nodex/

  e2e_agent:
    depends_on:
      mock_studio:
        condition: service_healthy
    image: ubuntu:22.04
    platform: linux/amd64
    volumes:
      - ./config:/root/.config/nodex/
      - agent_socket:/root/.nodex/
      - ./nodex-agent:/tmp/nodex-agent
    command: /tmp/nodex-agent controller
    environment:
      NODEX_DID_HTTP_ENDPOINT: http://mock_studio:8020
      NODEX_DID_ATTACHMENT_LINK: http://sidetree_prism:4010
      NODEX_STUDIO_HTTP_ENDPOINT: http://mock_studio:8020
      RUST_BACKTRACE: 1
    profiles:
      - e2e

  e2e_runner:
    depends_on:
      mock_studio:
        condition: service_healthy
    image: rust:latest
    platform: linux/amd64
    volumes:
      - ./config:/root/.config/nodex/
      - agent_socket:/root/.nodex/
      - ../:/tmp
    working_dir: /tmp/e2e
    environment:
      NODEX_DID_HTTP_ENDPOINT: http://mock_studio:8020
      NODEX_DID_ATTACHMENT_LINK: http://sidetree_prism:4010
      NODEX_STUDIO_HTTP_ENDPOINT: http://mock_studio:8020
      RUST_BACKTRACE: 1
    profiles:
      - e2e

networks:
  default:
    name: nodex-network

volumes:
  agent_socket:
