version: "3.9"

services:
  sidetree_prism:
    image: stoplight/prism:5.8.1
    platform: linux/amd64
    volumes:
      - ./did_sidetree.yaml:/tmp/api.yaml:ro
    ports:
      - "4010:4010"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4010/health || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache curl && chmod +x /usr/local/bin/prism && prism mock -h 0.0.0.0 /tmp/api.yaml"]

  studio_prism:
    image: stoplight/prism:5.8.1
    platform: linux/amd64
    volumes:
      - ./studio.yaml:/tmp/api.yaml:ro
    ports:
      - "8020:4010"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4010/health || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache curl && chmod +x /usr/local/bin/prism && prism mock -h 0.0.0.0 /tmp/api.yaml"]

  systemd_test:
    depends_on:
      sidetree_prism:
        condition: service_healthy
      studio_prism:
        condition: service_healthy
    build:
      context: .
      dockerfile: systemd/Dockerfile
    privileged: true
    profiles:
      - systemd
    volumes:
      - ./config:/root/.config/nodex/
      - agent_socket:/root/.nodex/

  e2e_agent:
    depends_on:
      sidetree_prism:
        condition: service_healthy
      studio_prism:
        condition: service_healthy
    image: ubuntu:20.04
    platform: linux/amd64
    volumes:
      - ./config:/root/.config/nodex/
      - agent_socket:/root/.nodex/
      - ./nodex-agent:/tmp/nodex-agent
    command: /tmp/nodex-agent
    environment:
      NODEX_DID_HTTP_ENDPOINT: http://sidetree_prism:4010
      NODEX_DID_ATTACHMENT_LINK: http://sidetree_prism:4010
      NODEX_STUDIO_HTTP_ENDPOINT: http://studio_prism:4010
      RUST_BACKTRACE: 1
    profiles:
      - e2e

  e2e_runner:
    depends_on:
      sidetree_prism:
        condition: service_healthy
      studio_prism:
        condition: service_healthy
    image: rust:slim-buster
    platform: linux/amd64
    volumes:
      - ./config:/root/.config/nodex/
      - agent_socket:/root/.nodex/
      - ../:/tmp
    working_dir: /tmp/e2e
    environment:
      NODEX_DID_HTTP_ENDPOINT: http://sidetree_prism:4010
      NODEX_DID_ATTACHMENT_LINK: http://sidetree_prism:4010
      NODEX_STUDIO_HTTP_ENDPOINT: http://studio_prism:4010
      RUST_BACKTRACE: 1
    profiles:
      - e2e

networks:
  default:
    name: nodex-network

volumes:
  agent_socket:
