openapi: "3.0.0"
info:
  version: 1.0.0
  title: DID Registry API
servers:
  - url: https://did.nodecross.io
paths:
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      tags:
        - health
      responses:
        "200":
          description: Expected response to a valid request

  /api/v1/identifiers/{did}:
    get:
      summary: Find a did
      operationId: findDID
      tags:
        - did
      parameters:
        - name: did
          in: path
          required: true
          description: The did to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DidResolutionResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/operations:
    post:
      summary: Create a new did
      operationId: createDID
      tags:
        - did
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DidCreateRequest"
      responses:
        "201":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DidResolutionResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    DidResolutionResponse:
      type: object
      required:
        - "@context"
        - didDocument
        - methodMetadata
      properties:
        "@context":
          type: string
          example: "https://www.w3.org/ns/did-resolution/v1"
        didDocument:
          $ref: "#/components/schemas/DidDocument"
        methodMetadata:
          $ref: "#/components/schemas/methodMetadata"

    DidDocument:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: "did:nodex:test:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        publicKey:
          type: array
          items:
            - $ref: "#/components/schemas/PublicKey"
            - $ref: "#/components/schemas/PublicKeyEnc"
        authentication:
          type: array
          items:
            type: string
          example: ["#signingKey", "#encryptionKey"]

    PublicKeyEnc:
      type: object
      required:
        - id
        - type
        - controller
        - publicKeyJwk
      properties:
        id:
          type: string
          example: "#encryptionKey"
        controller:
          type: string
          example: ""
        type:
          type: string
          example: "X25519KeyAgreementKey2019"
        publicKeyJwk:
          $ref: "#/components/schemas/PublicKeyJwkEnc"

    PublicKeyJwkEnc:
      type: object
      required:
        - kty
        - crv
        - x
      properties:
        kty:
          type: string
          example: "OKP"
        crv:
          type: string
          example: "X25519"
        x:
          type: string
          example: "UnWe6FZwUEK6_IwsjOiyL2VOBcKOSsc7kJlErzPI70c"

    PublicKey:
      type: object
      required:
        - id
        - type
        - controller
        - publicKeyJwk
      properties:
        id:
          type: string
          example: "#signingKey"
        controller:
          type: string
          example: ""
        type:
          type: string
          example: "EcdsaSecp256k1VerificationKey2019"
        publicKeyJwk:
          $ref: "#/components/schemas/PublicKeyJwk"

    PublicKeyJwk:
      type: object
      required:
        - kty
        - crv
        - x
        - y
      properties:
        kty:
          type: string
          example: "EC"
        crv:
          type: string
          example: "secp256k1"
        x:
          type: string
          example: "l52hoeJk9g5jwFJSQPbdoF43Ks8RAcXnnBWkJ4Cu0zU"
        y:
          type: string
          example: "QO1yc5ije5FnTP43BpIgTTsqYuWzGhZAmwND4pZ1BSE"

    methodMetadata:
      type: object
      properties:
        published:
          type: boolean
        recoveryCommitment:
          type: string
        updateCommitment:
          type: string

    DidCreateRequest:
      type: object
      required:
        - type
        - delta
        - suffix_data
      properties:
        type:
          type: string
        delta:
          type: string
        suffix_data:
          type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
