name: e2e test
description: "E2E test action"
inputs:
  binary-path:
    required: true
    description: "the path of the binary to be tested"
runs:
  using: composite
  steps:

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.1'

    - name: (setup) copy default config to home
      shell: powershell
      run: New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.config\nodex; Copy-Item test_resource\config\* $env:USERPROFILE\.config\nodex\

    - name: Install Prism CLI
      run: npm install -g @stoplight/prism-cli
      shell: powershell
  
    - name: Confirm prism
      run: prism --version
      shell: powershell

    - name: (run) Start Sidetree Prism Mock Server
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 10
        retry_on: error
        command: |
          Start-Process prism -ArgumentList "mock -h localhost -p 4010 ${github.workspace}/did_sidetree.yaml" -NoNewWindow -RedirectStandardOutput "prism_output.log" -RedirectStandardError "prism_error.log"
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri http://localhost:4010/health -UseBasicParsing

    - name: (run) Start Studio Prism Mock Server
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 10
        retry_on: error
        command: |
          Start-Process prism -ArgumentList "mock -h localhost -p 8020 ${github.workspace}/did_sidetree.yaml" -NoNewWindow -RedirectStandardOutput "prism_output.log" -RedirectStandardError "prism_error.log"
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri http://localhost:8020/health -UseBasicParsing

    - name: (run) run agent for e2e tests
      uses: nick-fields/retry@v3
      with:
        timeout_seconds: 120
        max_attempts: 10
        retry_on: error
        command: |
          Start-Process powershell -ArgumentList "${{ inputs.binary-path }}  -NoNewWindow -RedirectStandardOutput "agent.log"
          Start-Sleep -Seconds 10
          Invoke-WebRequest -Uri http://localhost:3000/health -UseBasicParsing
      env:
        NODEX_DID_HTTP_ENDPOINT: http://localhost:4010
        NODEX_DID_ATTACHMENT_LINK: http://localhost:4010
        NODEX_STUDIO_HTTP_ENDPOINT: http://localhost:8020
        NODEX_SERVER_PORT: 3000
        RUST_BACKTRACE: 1

    - name: (run) e2e tests
      shell: powershell
      working-directory: e2e
      run: cargo test

    - name: (run) shutdown agent by SIGINT
      shell: powershell
      run: |
        Get-Process nodex-agent | Stop-Process -Force
        Start-Sleep -Seconds 3

    - name: (run) Check for 'SIGINT' log message
      shell: powershell
      id: check_logs_for_sigint
      run: |
        if (Select-String -Path log.txt -Pattern "SIGINT") {
          echo "::set-output name=stopped_found::true"
        } else {
          echo "::set-output name=stopped_found::false"
        }

    - name: (run) Verify process is not running in e2e_agent by SIGINT
      shell: powershell
      if: steps.check_logs_for_sigint.outputs.stopped_found == 'true'
      run: $pids = (Get-Process -Name nodex-agent -ErrorAction SilentlyContinue)

    - name: (run) show log of mock server
      shell: bash
      run: Get-Content "prism_output.log"
      if: ${{ always() }}

    - name: (run) show log of mock server
      shell: bash
      run: Get-Content "prism_error.log"
      if: ${{ always() }}

    - name: (run) show log of agent
      shell: bash
      run: Get-Content "agent.log"
      if: ${{ always() }}
