name: e2e test
description: "E2E test action"
inputs:
  binary-path:
    required: true
    description: "the path of the binary to be tested"
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.0'

    - name: (setup) copy default config to home
      shell: powershell
      run: New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.config\nodex; Copy-Item test_resource\config\* $env:USERPROFILE\.config\nodex\

    - name: Install Prism CLI
      shell: powershell
      run: npm install -g @stoplight/prism-cli

    - name: Get Prism Path
      id: get-prism-path
      shell: powershell
      run: |
        $prismPath = Get-Command prism | Select-Object -ExpandProperty Source
        echo "::set-output name=prismPath::$prismPath"

    - name: Setup and Run Tests
      shell: powershell
      run: |
        $prismPath = "${{ steps.get-prism-path.outputs.prismPath }}"
        $sidetreeResourcePath = Join-Path -Path $PWD -ChildPath "test_resource/did_sidetree.yaml"
        $studioResourcePath = Join-Path -Path $PWD -ChildPath "test_resource/studio.yaml"

        Start-Process -NoNewWindow -FilePath "powershell" -ArgumentList "-File $prismPath mock -h 127.0.0.1 -p 4010 $sidetreeResourcePath"
        Start-Process -NoNewWindow -FilePath "powershell" -ArgumentList "-File $prismPath mock -h 127.0.0.1 -p 8020 $studioResourcePath"
        Start-Sleep -Seconds 10

        $agentPath = Join-Path -Path $PWD -ChildPath ${{ inputs.binary-path }}
        $stdErrLogTmp = Join-Path -Path $PWD -ChildPath ".\stderr.log"
        $stdOutLogTmp = Join-Path -Path $PWD -ChildPath ".\stdout.log"
        Start-Process -FilePath "$agentPath" -NoNewWindow -RedirectStandardOutput "$stdOutLogTmp" -RedirectStandardError "$stdErrLogTmp"
        Start-Sleep -Seconds 10

        cd e2e
        cargo test
      env:
        NODEX_DID_HTTP_ENDPOINT: http://127.0.0.1:4010
        NODEX_DID_ATTACHMENT_LINK: http://127.0.0.1:4010
        NODEX_STUDIO_HTTP_ENDPOINT: http://127.0.0.1:8020
        NODEX_SERVER_PORT: 3000
        RUST_BACKTRACE: 1

    - name: (run) show log of agent
      shell: powershell
      run: |
        $stdOutLogTmp = Join-Path -Path $PWD -ChildPath ".\stdout.log"
        Get-Content $stdOutLogTmp
        $stdErrLogTmp = Join-Path -Path $PWD -ChildPath ".\stderr.log"
        Get-Content $stdErrLogTmp
      if: ${{ always() }}
