name: e2e test
description: "E2E test action"
inputs:
  binary-path:
    required: true
    description: "the path of the binary to be tested"
runs:
  using: composite
  steps:

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.1'

    - name: (setup) copy default config to home
      shell: powershell
      run: New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.config\nodex; Copy-Item test_resource\config\* $env:USERPROFILE\.config\nodex\

    - name: Install Prism CLI
      shell: powershell
      run: npm install -g @stoplight/prism-cli

    - name: Get Prism Path
      id: get-prism-path
      shell: powershell
      run: |
        $prismPath = Get-Command prism | Select-Object -ExpandProperty Source
        echo "::set-output name=prismPath::$prismPath"

    - name: (run) Start Sidetree Prism Mock Server
      shell: powershell
      run: |
        $path = "${{ steps.get-prism-path.outputs.prismPath }}"
        $job = Start-Job -ScriptBlock {
          & "$using:path" mock -h 127.0.0.1 -p 4010 test_resource/did_sidetree.yaml
        }
        Start-Sleep -Seconds 5
        $jobState = Get-Job -Id $job.Id
        Write-Host "Job State: $($jobState.State)"
        if ($job.State -eq 'Completed') {
          $output = Receive-Job -Job $job
          Write-Host "Job Output: $output"
        }
        if ($jobState.State -eq 'Running') {
          $response = Invoke-RestMethod -Uri "http://127.0.0.1:4010/health" -Method Get -UseBasicParsing
          Write-Host "HTTP Status Code: $($response.StatusCode)"
          if ($response.StatusCode -ne 200) {
            Write-Host "Health check failed"
            exit 1
          }
        } else {
          Write-Host "Mock server did not start correctly"
          exit 1
        }

    - name: (run) Start Studio Prism Mock Server
      shell: powershell
      run: |
        $path = "${{ steps.get-prism-path.outputs.prismPath }}"
        $job = Start-Job -ScriptBlock {
            & "$using:path" mock -h 127.0.0.1 -p 8020 test_resource/studio.yaml
          }
        Start-Sleep -Seconds 5
        $jobState = Get-Job -Id $job.Id
        Write-Host "Job State: $($jobState.State)"
        if ($job.State -eq 'Completed') {
          $output = Receive-Job -Job $job
          Write-Host "Job Output: $output"
        }
        if ($jobState.State -eq 'Running') {
          $response = Invoke-RestMethod -Uri "http://127.0.0.1:8020/health" -Method Get -UseBasicParsing
          Write-Host "HTTP Status Code: $($response.StatusCode)"
          if ($response.StatusCode -ne 200) {
            Write-Host "Health check failed"
            exit 1
          }
        } else {
          Write-Host "Mock server did not start correctly"
          exit 1
        }

    - name: (run) run agent for e2e tests
      shell: powershell
      run: |
        $response = Invoke-RestMethod -Uri "http://127.0.0.1:4010/health" -Method Get -UseBasicParsing
        Write-Host "HTTP Status Code: $($response.StatusCode)"
        if ($response.StatusCode -ne 200) {
          Write-Host "Health check failed"
          exit 1
        }
        $job = Start-Job -ScriptBlock {
          param($path)
          & powershell -File $path
        } -ArgumentList "${{ inputs.binary-path }}"
        Start-Sleep -Seconds 10
        $jobState = Get-Job -Id $job.Id
        Write-Host "Job State: $($jobState.State)"
        if ($job.State -eq 'Completed') {
          $output = Receive-Job -Job $job
          Write-Host "Job Output: $output"
        }
        if ($jobState.State -eq 'Running') {
          $response = Invoke-RestMethod -Uri "http://127.0.0.1:3000" -Method Get -UseBasicParsing
          Write-Host "HTTP Status Code: $($response.StatusCode)"
          if ($response.StatusCode -ne 200) {
            Write-Host "Health check failed"
            exit 1
          }
        } else {
          Write-Host "Mock server did not start correctly"
          exit 1
        }
      env:
        NODEX_DID_HTTP_ENDPOINT: http://127.0.0.1:4010
        NODEX_DID_ATTACHMENT_LINK: http://127.0.0.1:4010
        NODEX_STUDIO_HTTP_ENDPOINT: http://127.0.0.1:8020
        NODEX_SERVER_PORT: 3000
        RUST_BACKTRACE: 1

    - name: (run) e2e tests
      shell: powershell
      working-directory: e2e
      run: cargo test

    - name: (run) shutdown agent by SIGINT
      shell: powershell
      run: |
        Get-Process nodex-agent | Stop-Process -Force
        Start-Sleep -Seconds 3

    - name: (run) Check for 'SIGINT' log message
      shell: powershell
      id: check_logs_for_sigint
      run: |
        if (Select-String -Path log.txt -Pattern "SIGINT") {
          echo "::set-output name=stopped_found::true"
        } else {
          echo "::set-output name=stopped_found::false"
        }

    - name: (run) Verify process is not running in e2e_agent by SIGINT
      shell: powershell
      if: steps.check_logs_for_sigint.outputs.stopped_found == 'true'
      run: $pids = (Get-Process -Name nodex-agent -ErrorAction SilentlyContinue)

    - name: (run) show log of agent
      shell: powershell
      run: Get-Content "agent.log"
      if: ${{ always() }}
