name: e2e test
description: "E2E test action"
inputs:
  binary-path:
    required: true
    description: "the path of the binary to be tested"
runs:
  using: composite
  steps:
    - name: (setup) copy default config to home
      shell: powershell
      run: New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.config\nodex; Copy-Item test_resource\localhost_config\* $env:USERPROFILE\.config\nodex\

    - name: Check and install Rust/Cargo if needed
      shell: powershell
      run: |
        # Check if cargo is available
        $cargoInstalled = $false
        try {
            cargo --version | Out-Null
            $cargoInstalled = $true
            Write-Host "Cargo is already installed"
        } catch {
            Write-Host "Cargo not found, will attempt to install"
        }

        # Install Rust/Cargo if not found
        if (-not $cargoInstalled) {
            Write-Host "Installing Rust and Cargo..."
            try {
                # Download the rustup-init.exe installer
                $rustupInitUrl = "https://win.rustup.rs/x86_64"
                $rustupInitPath = "$env:TEMP\rustup-init.exe"
                
                Invoke-WebRequest -Uri $rustupInitUrl -OutFile $rustupInitPath
                
                # Run the installer with default settings (silent install)
                & $rustupInitPath -y --default-toolchain stable --profile minimal
                
                # Update PATH to include cargo
                $env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"
                
                # Verify installation
                cargo --version
                if ($LASTEXITCODE -ne 0) {
                    throw "Cargo installation verification failed"
                }
                
                Write-Host "Rust and Cargo installed successfully"
            } catch {
                Write-Host "Failed to install Rust/Cargo: $_"
                exit 1
            }
        }

    - name: Start mock studio
      shell: powershell
      run: |
        # Navigate to mock studio directory
        Push-Location test_resource\mock_studio

        # Create separate log files for stdout and stderr
        New-Item -ItemType File -Force -Path "mock_studio_out.log" | Out-Null
        New-Item -ItemType File -Force -Path "mock_studio_err.log" | Out-Null

        # Ensure cargo is in PATH
        $env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"

        # Check if we need to build the mock studio first
        if (-not (Test-Path "Cargo.toml")) {
            Write-Host "Error: Cargo.toml not found in mock_studio directory"
            exit 1
        }

        # Run the mock server in the background with different files for stdout and stderr
        $env:PORT = "8020"
        Write-Host "Starting mock server on port 8020..."
        $mockServerProcess = Start-Process -FilePath "cargo" -ArgumentList "run" -NoNewWindow -PassThru -RedirectStandardOutput "mock_studio_out.log" -RedirectStandardError "mock_studio_err.log"

        # Save the PID for later cleanup
        $mockServerProcess.Id | Out-File -FilePath "mock_studio.pid"
        Write-Host "Mock server started with PID: $($mockServerProcess.Id)"

        # Return to original directory
        Pop-Location

        # Wait for the server to start
        Write-Host "Waiting for mock server to start on port 8020..."
        $maxRetries = 120
        $retryCount = 0
        $serverStarted = $false

        while (-not $serverStarted -and $retryCount -lt $maxRetries) {
            try {
                $connection = New-Object System.Net.Sockets.TcpClient("localhost", 8020)
                if ($connection.Connected) {
                    $serverStarted = $true
                    Write-Host "Mock server is up and running on port 8020"
                }
                try {
                    $response = Invoke-WebRequest -Uri "http://localhost:8020/health" -Method GET -TimeoutSec 5
                    Write-Host "Health check: $($response.StatusCode) $($response.StatusDescription)"
                } catch {
                    Write-Host "Warning: Server is listening but health endpoint may not be ready: $_"
                    Start-Sleep -Seconds 5
                }
                $connection.Close()
            } catch {
                $retryCount++
                Write-Host "Waiting for server to start (attempt $retryCount/$maxRetries)..."
                
                # Check if process is still running
                try {
                    $processStillRunning = Get-Process -Id $mockServerProcess.Id -ErrorAction SilentlyContinue
                    if (-not $processStillRunning) {
                        Write-Host "Error: Mock server process has terminated unexpectedly"
                        Get-Content test_resource\mock_studio\mock_studio_out.log
                        Get-Content test_resource\mock_studio\mock_studio_err.log
                        exit 1
                    }
                } catch {
                    Write-Host "Error: Could not check mock server process status"
                    Get-Content test_resource\mock_studio\mock_studio_out.log
                    Get-Content test_resource\mock_studio\mock_studio_err.log
                    exit 1
                }
                
                if ($retryCount -eq $maxRetries) {
                    Write-Host "Timed out waiting for mock server to start"
                    Get-Content test_resource\mock_studio\mock_studio_out.log
                    Get-Content test_resource\mock_studio\mock_studio_err.log
                    exit 1
                }
                
                Start-Sleep -Seconds 5
                
                # Check log periodically
                if ($retryCount % 10 -eq 0) {
                    Write-Host "=== Current mock server stdout ==="
                    Get-Content test_resource\mock_studio\mock_studio_out.log -Tail 20
                    Write-Host "=== Current mock server stderr ==="
                    Get-Content test_resource\mock_studio\mock_studio_err.log -Tail 20
                }
            }
        }

    - name: Setup and Run Tests
      shell: powershell
      run: |
        # Ensure the binary exists
        if (-not (Test-Path "${{ inputs.binary-path }}")) {
            Write-Host "Error: Binary not found at ${{ inputs.binary-path }}"
            exit 1
        }

        # Create separate log files for stdout and stderr
        New-Item -ItemType File -Force -Path "agent_out.log" | Out-Null
        New-Item -ItemType File -Force -Path "agent_err.log" | Out-Null

        # Start the agent in background
        Write-Host "Starting agent ..."
        $agentProcess = Start-Process -FilePath "${{ inputs.binary-path }}" -NoNewWindow -PassThru -RedirectStandardOutput "agent_out.log" -RedirectStandardError "agent_err.log"
        $agentProcessId = $agentProcess.Id
        Write-Host "Agent started with PID: $agentProcessId"

        # Give it time to initialize
        Write-Host "Waiting for agent to initialize..."
        Start-Sleep -Seconds 30

        # Ensure cargo is in PATH for running tests
        $env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"

        # Run tests
        Write-Host "Running cargo tests..."
        Push-Location e2e
        $testResult = $null
        try {
            cargo test
            $testResult = $?
        } catch {
            $testResult = $false
            Write-Host "Error running tests: $_"
        }
        Pop-Location

        # Store test result for later evaluation
        $testsPassed = $testResult

        # Send SIGINT (equivalent to CTRL+C on Windows)
        Write-Host "Sending termination signal to agent process (PID: $agentProcessId)..."
        try {
            Stop-Process -Id $agentProcessId -Force
        } catch {
            Write-Host "Warning: Failed to stop agent process: $_"
        }

        # Wait for process to handle signal
        Write-Host "Waiting for agent to process signal..."
        Start-Sleep -Seconds 5

        # Check if SIGINT appears in either of the logs
        Write-Host "Checking for SIGINT in log files..."
        $outLogContent = Get-Content agent_out.log -Raw -ErrorAction SilentlyContinue
        $errLogContent = Get-Content agent_err.log -Raw -ErrorAction SilentlyContinue

        if (($outLogContent -match "SIGINT") -or ($errLogContent -match "SIGINT")) {
            Write-Host "SIGINT found in log as expected."
        } else {
            Write-Host "Error: SIGINT not found in logs."
            exit 1
        }

        # Verify process has terminated
        Write-Host "Verifying agent process has terminated..."
        try {
            $processExists = Get-Process -Id $agentProcessId -ErrorAction SilentlyContinue
            if ($processExists) {
                Write-Host "Error: Process is still running, which is not expected."
                exit 1
            } else {
                Write-Host "Process terminated as expected."
            }
        } catch {
            Write-Host "Process not found, as expected."
        }

        # Now evaluate test result
        if (-not $testsPassed) {
            Write-Host "Error: Tests did not pass."
            exit 1
        }
      env:
        NODEX_DID_HTTP_ENDPOINT: http://127.0.0.1:8020
        NODEX_DID_ATTACHMENT_LINK: http://127.0.0.1:4010
        NODEX_STUDIO_HTTP_ENDPOINT: http://127.0.0.1:8020
        NODEX_SERVER_PORT: 3000
        RUST_BACKTRACE: full

    - name: Stop mock studio
      shell: powershell
      run: |
        # Look for the PID file
        $mockServerPidFile = "test_resource\mock_studio\mock_studio.pid"
        if (Test-Path $mockServerPidFile) {
            $serverProcessId = Get-Content $mockServerPidFile
            Write-Host "Stopping mock server (PID: $serverProcessId)..."
            try {
                # Terminate the process
                Stop-Process -Id $serverProcessId -Force -ErrorAction SilentlyContinue
                Write-Host "Mock server process (PID: $serverProcessId) stopped"
                Remove-Item $mockServerPidFile -Force -ErrorAction SilentlyContinue
            } catch {
                Write-Host "Failed to stop mock server process or process already stopped"
            }
        } else {
            Write-Host "Mock server PID file not found."
        }
      if: ${{ always() }}

    - name: (run) show log of agent
      shell: powershell
      run: |
        Write-Host "=== Agent Standard Output ==="
        if (Test-Path "agent_out.log") {
            Get-Content agent_out.log
        } else {
            Write-Host "Warning: Agent stdout log file not found"
        }

        Write-Host "=== Agent Standard Error ==="
        if (Test-Path "agent_err.log") {
            Get-Content agent_err.log
        } else {
            Write-Host "Warning: Agent stderr log file not found"
        }
      if: ${{ always() }}

    - name: (run) show log of mock studio
      shell: powershell
      run: |
        Write-Host "=== Mock Studio Standard Output ==="
        $outLogPath = "test_resource\mock_studio\mock_studio_out.log"
        if (Test-Path $outLogPath) {
            Get-Content $outLogPath
        } else {
            Write-Host "Warning: Mock studio stdout log file not found"
        }

        Write-Host "=== Mock Studio Standard Error ==="
        $errLogPath = "test_resource\mock_studio\mock_studio_err.log"
        if (Test-Path $errLogPath) {
            Get-Content $errLogPath
        } else {
            Write-Host "Warning: Mock studio stderr log file not found"
        }
      if: ${{ always() }}
