name: e2e test
description: "E2E test action"
inputs:
  binary-path:
    required: true
    description: "the path of the binary to be tested"
runs:
  using: composite
  steps:
    - name: (setup) copy default config to home
      shell: powershell
      run: New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.config\nodex; Copy-Item test_resource\localhost_config\* $env:USERPROFILE\.config\nodex\

    - name: Setup and Run Tests
      shell: powershell
      run: |
        $agentPath = Join-Path -Path $PWD -ChildPath ${{ inputs.binary-path }}
        $stdErrLogTmp = Join-Path -Path $PWD -ChildPath ".\stderr.log"
        $stdOutLogTmp = Join-Path -Path $PWD -ChildPath ".\stdout.log"
        Start-Process -FilePath "$agentPath" -NoNewWindow -RedirectStandardOutput "$stdOutLogTmp" -RedirectStandardError "$stdErrLogTmp"
        Start-Sleep -Seconds 10

        cd e2e
        cargo test
      env:
        NODEX_DID_HTTP_ENDPOINT: http://127.0.0.1:8020
        NODEX_DID_ATTACHMENT_LINK: http://127.0.0.1:4010
        NODEX_STUDIO_HTTP_ENDPOINT: http://127.0.0.1:8020
        NODEX_SERVER_PORT: 3000
        RUST_BACKTRACE: full

    - name: (run) show log of agent
      shell: powershell
      run: |
        $stdOutLogTmp = Join-Path -Path $PWD -ChildPath ".\stdout.log"
        Get-Content $stdOutLogTmp
        $stdErrLogTmp = Join-Path -Path $PWD -ChildPath ".\stderr.log"
        Get-Content $stdErrLogTmp
      if: ${{ always() }}
