name: e2e test
description: "E2E test action"
inputs:
  binary-path:
    required: true
    description: "the path of the binary to be tested"
runs:
  using: composite
  steps:
    - name: (setup) copy default config to home
      shell: powershell
      run: New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.config\nodex; Copy-Item test_resource\localhost_config\* $env:USERPROFILE\.config\nodex\

    - name: Start mock server
      shell: powershell
      run: |
        $mockServerDir = Join-Path -Path $PWD -ChildPath "test_resource\mock_studio"
        $mockServerLogPath = Join-Path -Path $mockServerDir -ChildPath "mock_studio.log"

        # Change to the mock server directory
        Push-Location $mockServerDir

        # Start the mock server with PORT=8020
        $env:PORT = "8020"
        $mockServerProcess = Start-Process -FilePath "npm" -ArgumentList "start" -NoNewWindow -PassThru -RedirectStandardOutput $mockServerLogPath -RedirectStandardError $mockServerLogPath

        # Save the process ID for later cleanup
        $mockServerProcess.Id | Out-File -FilePath "mock_studio.pid"

        # Return to the original directory
        Pop-Location

        # Wait for the mock server to start
        Write-Host "Waiting for mock server to start on port 8020..."
        $maxRetries = 60
        $retryCount = 0
        $serverStarted = $false

        while (-not $serverStarted -and $retryCount -lt $maxRetries) {
            try {
                $connection = New-Object System.Net.Sockets.TcpClient("127.0.0.1", 8020)
                if ($connection.Connected) {
                    $serverStarted = $true
                    Write-Host "Mock server is up and running on port 8020"
                }
                $connection.Close()
            } catch {
                $retryCount++
                Start-Sleep -Seconds 5
            }
        }

        if (-not $serverStarted) {
            Write-Host "Timed out waiting for mock server to start"
            Get-Content $mockServerLogPath
            exit 1
        }

    - name: Setup and Run Tests
      shell: powershell
      run: |
        $agentPath = Join-Path -Path $PWD -ChildPath ${{ inputs.binary-path }}
        $stdErrLogTmp = Join-Path -Path $PWD -ChildPath ".\stderr.log"
        $stdOutLogTmp = Join-Path -Path $PWD -ChildPath ".\stdout.log"
        Start-Process -FilePath "$agentPath" -NoNewWindow -RedirectStandardOutput "$stdOutLogTmp" -RedirectStandardError "$stdErrLogTmp"
        Start-Sleep -Seconds 10

        cd e2e
        cargo test
      env:
        NODEX_DID_HTTP_ENDPOINT: http://127.0.0.1:8020
        NODEX_DID_ATTACHMENT_LINK: http://127.0.0.1:4010
        NODEX_STUDIO_HTTP_ENDPOINT: http://127.0.0.1:8020
        NODEX_SERVER_PORT: 3000
        RUST_BACKTRACE: full

    - name: Stop mock server
      shell: powershell
      run: |
        $mockServerPidFile = Join-Path -Path $PWD -ChildPath "test_resource\mock_studio\mock_studio.pid"
        if (Test-Path $mockServerPidFile) {
            $pid = Get-Content $mockServerPidFile
            try {
                Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
                Write-Host "Mock server process (PID: $pid) stopped"
            } catch {
                Write-Host "Failed to stop mock server process or process already stopped"
            }
            Remove-Item $mockServerPidFile -Force -ErrorAction SilentlyContinue
        }
      if: ${{ always() }}

    - name: (run) show log of agent
      shell: powershell
      run: |
        $stdOutLogTmp = Join-Path -Path $PWD -ChildPath ".\stdout.log"
        Get-Content $stdOutLogTmp
        $stdErrLogTmp = Join-Path -Path $PWD -ChildPath ".\stderr.log"
        Get-Content $stdErrLogTmp
      if: ${{ always() }}

    - name: (run) show log of mock server
      shell: powershell
      run: |
        $mockServerLogPath = Join-Path -Path $PWD -ChildPath "test_resource\mock_studio\mock_studio.log"
        Get-Content $mockServerLogPath
      if: ${{ always() }}
