name: e2e test
description: "E2E test action"
inputs:
  binary-path:
    required: true
    description: "the path of the binary to be tested"
runs:
  using: composite
  steps:

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: (setup) copy default config to home
      shell: powershell
      run: New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.config\nodex; Copy-Item test_resource\config\* $env:USERPROFILE\.config\nodex\

    - name: Install Prism CLI
      run: npm install -g @stoplight/prism-cli
      shell: powershell

    - name: Start Sidetree Prism Mock Server
      run: |
        Start-Process prism -ArgumentList "mock -h 0.0.0.0 -p 4010 ${github.workspace}/did_sidetree.yaml"
        Start-Sleep -Seconds 5
        $response = Invoke-WebRequest -Uri http://localhost:4010/health -UseBasicParsing
        if ($response.StatusCode -ne 200) {
          throw "Health check failed"
        }
      shell: powershell

    - name: Start Studio Prism Mock Server
      run: |
        Start-Process prism -ArgumentList "mock -h 0.0.0.0 -p 8020 ${github.workspace}/studio.yaml"
        Start-Sleep -Seconds 5
        $response = Invoke-WebRequest -Uri http://localhost:8020/health -UseBasicParsing
        if ($response.StatusCode -ne 200) {
          throw "Health check for Sidetree Prism failed"
        }
      shell: powershell

    - name: (run) run agent for e2e tests
      uses: nick-fields/retry@v3
      with:
        timeout_seconds: 120
        max_attempts: 10
        retry_on: error
        command: |
          Start-Process powershell -ArgumentList "${{ inputs.binary-path }} > log.txt 2>&1 &"
          Start-Sleep -Seconds 3
          $response = Invoke-WebRequest -Uri http://localhost:8020/health -UseBasicParsing
          if ($response.StatusCode -ne 200) {
            throw "Health check for Studio Prism failed"
          }
      env:
        NODEX_DID_HTTP_ENDPOINT: http://localhost:4010
        NODEX_DID_ATTACHMENT_LINK: http://localhost:4010
        NODEX_STUDIO_HTTP_ENDPOINT: http://localhost:8020
        NODEX_SERVER_PORT: 3000
        RUST_BACKTRACE: 1

    - name: (run) e2e tests
      shell: powershell
      working-directory: e2e
      run: cargo test

    - name: (run) shutdown agent by SIGINT
      shell: powershell
      run: |
        Get-Process nodex-agent | Stop-Process -Force
        Start-Sleep -Seconds 3
      if: ${{ always() }}

    - name: (run) Check for 'SIGINT' log message
      shell: powershell
      id: check_logs_for_sigint
      run: |
        if (Select-String -Path log.txt -Pattern "SIGINT") {
          echo "::set-output name=stopped_found::true"
        } else {
          echo "::set-output name=stopped_found::false"
        }

    - name: (run) Verify process is not running in e2e_agent by SIGINT
      shell: powershell
      if: steps.check_logs_for_sigint.outputs.stopped_found == 'true'
      run: |
        $pids = (Get-Process -Name nodex-agent -ErrorAction Sil
