[formatting]
align_comments = false
allowed_blank_lines = 1
array_auto_collapse = false
array_auto_expand = false
include = ["*.toml"]
indent_string = "    " # 4 spaces
keys = ["dependencies"]
reorder_arrays = true
reorder_keys = true
