name: Check Team affiliation and branch
description: Check Team affiliation and Branch

inputs:
  ref:
    required: true
    description: ""
  actor:
    required: true
    description: ""
  github_token:
    required: true
    description: secret.GITHUB_TOKEN

runs:
  using: composite
  steps:
    - name: Stop workflow if not on v1 branch
      if: ${{ inputs.ref != 'refs/heads/v1' }}
      shell: bash
      run: |
        echo "This job is only allowed to run on the v1 branch."
        exit 1

    - name: Check user for team affiliation
      uses: tspascoal/get-user-teams-membership@v2
      id: teamAffiliation
      with:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        username: ${{ github.actor }}
        team: maintainer

    - name: Stop workflow if user is no member
      if: ${{ steps.teamAffiliation.outputs.isTeamMember == 'false' }}
      shell: bash
      run: |
        echo "You have no rights to trigger this job."
        exit 1
