name: create-tag
description: ""
inputs:
  github-token:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v2

    - name: (setup) environment
      uses: ./.github/actions/shared

    - name: (run) commit analyzer
      id: commit_analyzer
      uses: ./.github/actions/commit-analyzer

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: "v${{ steps.commit_analyzer.outputs.VERSION }}"
        tag_exists_error: false