[package]
authors = { workspace = true }
edition = { workspace = true }
name = "protocol"
version = "0.4.0"

[dependencies]
chrono = { workspace = true }
cuid = { workspace = true }
data-encoding = { workspace = true }
didcomm-rs = { git = "https://github.com/nodecross/didcomm-rs.git", tag = "v0.8.1", default-features = false, features = [
    "raw-crypto",
] }
hex = { workspace = true }
http = { workspace = true }
k256 = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true }
serde_jcs = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
trait-variant = { workspace = true }
x25519-dalek = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
actix-rt = { workspace = true }
rand = "0.8.5"
