name: build with cross
description: ""
inputs:
  target:
    required: true
    description: ""
  use-cache:
    required: true
    description: ""
  checkout:
    required: false
    description: ""
  binary-file-name:
    required: true
    description: ""
  github-token:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: (checkout) source code
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: (cache) rust
      if: ${{ inputs.use-cache == 'true' }}
      uses: Swatinem/rust-cache@v2

    - name: (install) install development tools
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-llvm-cov,cross

    - name: (run) build
      shell: bash
      run: cross build --target ${{ inputs.target }} --release

    - name: (run) create artifact
      uses: vimtor/action-zip@v1.1
      with:
        files: target/${{ inputs.target }}/release/${{ inputs.binary-file-name }}
        dest: nodex-agent-${{ inputs.target }}.zip

    - name: (run) upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.target }}
        path: nodex-agent-${{ inputs.target }}.zip
