FROM --platform=linux/amd64 ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main-centos

# The pre-installed gcc compiler is too old and causes this problem.
# https://github.com/briansmith/ring/issues/1789
# so we update the gcc compiler
RUN yum update & yum install -y gcc
