FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main

RUN apt-get update && \
    apt-get install -y gcc-10 g++-10 libssl-dev pkg-config && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
                        --slave /usr/bin/g++ g++ /usr/bin/g++-10 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
