name: lint
description: ""
inputs:
  checkout:
    required: false
    description: ""
  github-token:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: (checkout) source code
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v4

    - name: (check) lint-rs
      shell: bash
      run: |
        cargo fmt --all -- --check
        cargo clippy -- -D warnings

    - name: (check) install-taplo
      uses: taiki-e/install-action@v2
      with:
        tool: taplo-cli

    - name: (check) lint-toml
      shell: bash
      run: |
        taplo lint
        taplo format --check
