[package]
name = "controller"
authors.workspace = true
categories.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { workspace = true }
dirs = { workspace = true }
fs2 = { workspace = true }
lazy_static = "1.4"
nix = { version = "0.29", features = ["fs", "signal", "process"] }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
serde_yaml = "0.9.34"
shadow-rs = { workspace = true }
thiserror = { workspace = true }
glob = "0.3.1"
