name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        description: "Major, minor or patch version bump"
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install `cargo-edit`
        run: cargo install cargo-edit

      - name: Install `cargo-get`
        run: cargo install cargo-get

      - id: cargo-set-version
        name: Set Version
        run: cargo set-version --bump ${{ inputs.version }} --exclude protocol

      - name: Set Crate Version as Environment Variable
        id: set_crate_version
        run: |
          CARGO_TOML_VERSION=$(cargo get workspace.package.version)
          echo "version=$CARGO_TOML_VERSION" >> $GITHUB_OUTPUT

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: bump version to v${{ steps.set_crate_version.outputs.version }}"
          branch: "chore/bump-version-to-v${{ steps.set_crate_version.outputs.version }}"
          delete-branch: true
          title: "chore: bump version to v${{ steps.set_crate_version.outputs.version }}"
          body: |
            Bumps the version to v${{ steps.set_crate_version.outputs.version }}.
          token: ${{ secrets.GITHUB_TOKEN }}
